# Generated by Django 4.1.3 on 2022-11-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.CharField(max_length=500)),
                ('album', models.CharField(max_length=500)),
                ('thumb', models.ImageField(upload_to='music_images/')),
                ('categoria', models.CharField(blank=True, choices=[('forro', 'Forró'), ('rock', 'Rock')], max_length=15, null=True)),
            ],
        ),
    ]
